### ISSUE TITLE
$PASSWORD's value?

### ISSUE THREAD

**Issue by VanshShah1411** [ivang7/heroku-vscode#2]
i have code-server stable but i can't login because i don't know the password so can anyone help me to do that any in latest builds i tried to run java but i was not able to the extension pack was successfully installed but when tried to create project it showed to error. so plz. help with this

**Comment by garyhtou** [comment]
If you deployed this repo via Heroku, I believe the password should have been auto-generated. You can find this auto-generate in the [config vars](https://devcenter.heroku.com/articles/config-vars#using-the-heroku-dashboard).

**Comment by VanshShah1411** [comment]
Yep I got that but i can't run any programs I can install the extension but when I create a file with that extension it will give error and I think that error is related to the language installation cna you help me with that?

**Comment by garyhtou** [comment]
Unfortunately, I don't know much about the inner workings of code-server. I suggest you ask on their repo ([https://github.com/cdr/code-server](https://github.com/cdr/code-server)).

**Comment by VanshShah1411** [comment]
Can you help me host code-server on heroku because I tried and got error. Plz. Can you help?

**Comment by ivang7** [comment]
for the stable version the password was previously generated, I changed to set the password manually in #5 

create new heroku app by button
