### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by violetbuse** [ivang7/heroku-vscode#4]
I tried the one-click-deploy button, and got this error code while building : 

Step 9/14 : RUN cd /tmp &&   curl -L --silent   `curl --silent "https://api.github.com/repos/cdr/code-server/releases/latest"     | grep '"browser_download_url":'     | grep "linux-x86_64"     |  sed -E 's/.*"([^"]+)".*/\1/'   `| tar -xzf - &&   mv code-server* /usr/local/lib/code-server &&   ln -s /usr/local/lib/code-server/code-server /usr/local/bin/code-server
 ---> Running in e8cb5338b428
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c cd /tmp &&   curl -L --silent   `curl --silent "https://api.github.com/repos/cdr/code-server/releases/latest"     | grep '"browser_download_url":'     | grep "linux-x86_64"     |  sed -E 's/.*"([^"]+)".*/\1/'   `| tar -xzf - &&   mv code-server* /usr/local/lib/code-server &&   ln -s /usr/local/lib/code-server/code-server /usr/local/bin/code-server' returned a non-zero code: 2

**Comment by ivang7** [comment]
hi, i tried to run app on heroku today and i got no error, app started successfull.

please try again.

if you want, i can create an app and transfer it to you

**Comment by ivang7** [comment]
stable version has been broken, i fix it in #5
